{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: datamind-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datamind-gateway
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
---
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: datamind-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels: {app: datamind-gateway}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: datamind-dataplane
spec:
  minAvailable: 1
  selector:
    matchLabels: {app: datamind-dataplane}
